# Generated by Django 3.2.9 on 2021-11-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='listings', to='auctions.categories'),
        ),
    ]
